=encoding UTF-8

=head1 NAME

bluecloth - convert Markdown input to HTLM

=head1 SYNOPSIS

B<bluecloth> [I<OPTIONS>] I<FILES>

=head1 DESCRIPTION

B<bluecloth> converts input files, supposed to be written in the Markdown
markup language. If no file is given, then it will read from the standard
input. B<bluecloth> then writes to the standard output a HTML file by
converting Mardown syntax using bluecloth ruby library.


=head1 OPTIONS

=over

=item   B<-d>, B<--debug>

Turn debugging output on

=item B<-f>, B<--fragment>

Output HTML fragments instead of whole documents

=back

=head1 AUTHORS

B<bluecloth> has been developed by Michael Granger. 

This manual page has been written for the Debian Project by Cédric Boutillier (but
may used by others). 
